#########################
# Model Configurations  #
#########################

ROOT: '/home/yuewen/projects/data/'
LOG: '/home/yuewen/code/ltcl-main-try/ckpoint/logs'
DATASET: 'linear_nongaussian_ts'

SPLINE:
    USE_WARM_START: TRUE
    TYPE: 'laplacian'
    STEPS: 5000
    LR: 0.001
    CUDA: FALSE
    BS: 64
    LATENT_DIM: 8
    BOUND: 5
    BINS: 8
    ORDER: 'linear'
    PATH: '/home/yuewen/code/ltcl-main-try/ckpoint/spline/spline_linear_nongau_ts.pth'
  
VAE:
    GPU: [0]
    CPU: 8
    TRAIN_BS: 128
    VAL_BS: 256
    EPOCHS: 200
    N_VAL_SAMPLES: 5000
    LAG: 2
    LR: 0.001
    BETA: 2
    GAMMA: 0.001
    ALPHA: 0.1
    INPUT_DIM: 8
    LATENT_DIM: 8
    DIAG: FALSE
    BIAS: FALSE
    ENC:
        HIDDEN_DIM: 128
    DEC:
        HIDDEN_DIM: 128
        DIST: 'gaussian'
    PIN: TRUE

MCC:
    FREQ: 0.1
    CORR: 'Pearson' # 'Spearman' # 
