#########################
# Model Configurations  #
#########################

ROOT: '/srv/data/ltcl/data'
LOG: '/srv/data/ltcl/log'
DATASET: 'physics_ball_5_s1'

SPLINE:
    USE_WARM_START: TRUE
    TYPE: 'laplacian'
    STEPS: 5000
    LR: 0.001
    CUDA: FALSE
    BS: 64
    LATENT_DIM: 10
    BOUND: 5
    BINS: 8
    ORDER: 'linear'
    PATH: '/srv/data/ltcl/ckpts/spline_mbi_5_ball.pth'

VAE:
    GPU: [0]
    CPU: 8
    TRAIN_BS: 32
    VAL_BS: 64
    EPOCHS: 1
    N_VAL_SAMPLES: 640
    LAG: 2
    LR: 1.0e-3
    BETA: 1
    GAMMA: 25
    L1: 0.001
    NC: 3
    LATENT_DIM: 10
    DIAG: TRUE
    IDENTITY: FALSE
    BIAS: FALSE # For non-white noise situations, enable bias
    ENC:
        HIDDEN_DIM: 512
    DEC:
        DIST: 'gaussian'
    PIN: TRUE

MCC:
    FREQ: 0.01
    CORR: 'Pearson' # 'Spearman'