#########################
# Model Configurations  #
#########################

ROOT: '/srv/data/ltcl/data'
LOG: '/srv/data/ltcl/log'
DATASET: 'kitti'
TRANSFORM: null
DT: 15

SPLINE:
    USE_WARM_START: TRUE
    TYPE: 'laplacian'
    STEPS: 5000
    LR: 0.001
    CUDA: TRUE
    BS: 64
    LATENT_DIM: 10
    BOUND: 5
    BINS: 8
    ORDER: 'linear'
    PATH: '/srv/data/ltcl/ckpts/spline_kitti.pth'
  
VAE:
    GPU: [0]
    CPU: 8
    TRAIN_BS: 64
    VAL_BS: 128
    EPOCHS: 200
    N_VAL_SAMPLES: 1280
    LAG: 1
    LENGTH: 1 # Future length
    TRANS_PRIOR: 'L'
    INFER_MODE: 'F'
    LR: 1.0E-3
    BETA: 0.1
    GAMMA: 25
    SIGMA: 1.0E-6
    L1: 0.1
    NC: 1
    LATENT_DIM: 10
    CAUSAL_DIM: 10
    BIAS: FALSE # For non-white noise situations, enable bias
    DIAG: FALSE
    ENC:
        HIDDEN_DIM: 512
    DEC:
        DIST: 'bernoulli'
    PIN: TRUE

MCC:
    FREQ: 0.5
    CORR: 'Spearman'