#########################
# Model Configurations  #
#########################

ROOT: '/home/cmu_wyao/projects/data/'
LOG: '/data/datasets/logs'
DATASET: 'kitti'
TRANSFORM: null
DT: 15

SPLINE:
    USE_WARM_START: TRUE
    TYPE: 'laplacian'
    STEPS: 5000
    LR: 0.001
    CUDA: TRUE
    BS: 64
    BOUND: 5
    BINS: 8
    ORDER: 'linear'
    PATH: '/home/cmu_wyao/spline_10.pth'
  
VAE:
    GPU: [2]
    CPU: 8
    TRAIN_BS: 64
    VAL_BS: 1280
    EPOCHS: 100
    N_VAL_SAMPLES: 1280
    LAG: 1
    LR: 0.001
    BETA: 0.1
    GAMMA: 25
    L1: 0.1
    NC: 1
    LATENT_DIM: 10
    DIAG: FALSE
    BIAS: FALSE # For non-white noise situations, enable bias
    ENC:
        HIDDEN_DIM: 512
    DEC:
        DIST: 'bernoulli'
    PIN: TRUE

MCC:
    FREQ: 0.5
    CORR: 'Spearman'