#########################
# Model Configurations  #
#########################

ROOT: '/srv/data/ltcl/data'
LOG: '/srv/data/ltcl/log'
DATASET: 'physics_ball_5_s1'

SPLINE:
    USE_WARM_START: TRUE
    TYPE: 'laplacian'
    STEPS: 5000
    LR: 0.001
    CUDA: FALSE
    BS: 64
    LATENT_DIM: 10
    BOUND: 5
    BINS: 8
    ORDER: 'linear'
    PATH: '/srv/data/ltcl/ckpts/spline_mbi_5_ball.pth'

KEYPOINTER:
    PATH: '/srv/data/ltcl/log/weiran/kp_5_ball/lightning_logs/version_3/checkpoints/epoch=9-step=366890.ckpt'
    N_KPS: 5
    WIDTH: 64
    HEIGHT: 64
    NF: 16
    NORM: 'batch'
    LIM: [-5., 5., -5., 5.]

VAE:
    GPU: [1]
    CPU: 8
    TRAIN_BS: 32
    VAL_BS: 128
    EPOCHS: 300
    N_VAL_SAMPLES: 1024
    NC: 3
    LAG: 2
    LENGTH: 4
    N_KPS: 5
    NCLASS: 50
    TRANS_PRIOR: 'NP'
    LR: 5.0e-3
    BETA: 1.0e-3
    GAMMA: 1.0e-2
    SIGMA: 1.0e-7
    L1: 1.0e-3
    LATENT_DIM: 2
    ENC:
        HIDDEN_DIM: 8
    DEC:
        HIDDEN_DIM: 8
        DIST: 'gaussian'
    PIN: TRUE

MCC:
    FREQ: 0.01
    CORR: 'Pearson' # 'Spearman'