#########################
# Model Configurations  #
#########################

ROOT: '/srv/data/ltcl/data'
LOG: '/srv/data/ltcl/log'
DATASET: 'physics_ball_5_s1'

MODEL: 'PCL'

PCL:
    GPU: [0]
    CPU: 8
    NC: 3
    K: 5
    NF: 16
    LAG: 2
    LENGTH: 2
    TRAIN_BS: 32
    VAL_BS: 64
    N_VAL_SAMPLES: 640
    EPOCHS: 1
    LR: 5.0E-4
    HIDDEN_DIM: 512
    SCORE_LAYER: 4
    PIN: TRUE

MCC:
    FREQ: 0.01
    CORR: 'Pearson' # 'Spearman'