#########################
# Model Configurations  #
#########################

ROOT: '/srv/data/ltcl/data'
LOG: '/srv/data/ltcl/log'
DATASET: 'mocap_point_cloud'

NS: FALSE
MODEL: 'PCL'
# MODEL: 'PCL'
# MODEL: 'iVAE' 
# MODEL: 'BetaVAE' 
# MODEL: 'SlowVAE' 
# MODEL: 'FactorVAE'

PCL:
    GPU: [1]
    CPU: 8
    LATENT_DIM: 3
    INPUT_DIM: 62
    TRAIN_BS: 32
    VAL_BS: 128
    N_VAL_SAMPLES: 1280
    EPOCHS: 200
    LR: 5.0E-4
    LAG: 2
    HIDDEN_DIM: 128
    ENCODER_LAYER: 4
    SCORE_LAYER: 4
    PIN: TRUE

MCC:
    FREQ: 1.0
    CORR: 'Pearson' # 'Spearman' # 