#########################
# Model Configurations  #
#########################

ROOT: '/srv/data/ltcl/data'
LOG: '/srv/data/ltcl/log'
DATASET: 'mocap_point_cloud'

SPLINE:
    USE_WARM_START: TRUE
    TYPE: 'gaussian'
    STEPS: 5000
    LR: 0.001
    CUDA: FALSE
    BS: 64
    LATENT_DIM: 8
    BOUND: 5
    BINS: 8
    ORDER: 'linear'
    PATH: '/srv/data/ltcl/ckpts/mocap_8.pth'
  
VAE:
    GPU: [1]
    CPU: 8
    TRAIN_BS: 32
    VAL_BS: 128
    EPOCHS: 200
    N_VAL_SAMPLES: 1280
    LAG: 2
    LENGTH: 4
    NCLASS: 12
    TRANS_PRIOR: 'NP'
    LR: 1.0e-3
    BETA: 1.0e-1
    GAMMA: 1
    SIGMA: 1.0e-6
    L1: 1.0e-3
    INPUT_DIM: 62
    LATENT_DIM: 8
    BIAS: FALSE
    ENC:
        HIDDEN_DIM: 128
    DEC:
        HIDDEN_DIM: 128
        DIST: 'gaussian'
    PIN: TRUE